FROM node:20


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN mkdir -p /usr/src/app/prisma 

RUN npx prisma generate

RUN npm install bcrypt

RUN npm run build

EXPOSE 3020

CMD npx prisma db push && npm start