export const dados = {
  dimensao: ["EXECUTIVA", "GERES", "MUNICÍPIOS"],
  origem: ["OFICINA GpR", "GABINETE DGPP"],
  tema: [
    "FINANCEIRO / ORÇAMENTO",
    "GERES PErcorre",
    "PERDA PRIMÁRIA / REGULAÇÃO",
    "PES",
    "PQAVS",
    "REGULAÇÃO",
    "PLANEJAMENTO",
    "PRI/GOVERNANÇA",
    "GOVERNANÇA",
  ],
  indicador: [
    "% DE EXECUÇÃO DO ORÇAMENTO POR REGIONAL",
    "TAXA DE SATISFAÇÃO DOS MUNICÍPIOS EM RELAÇÃO AO APOIO DAS GERES",
    "% DE RESOLUÇÃO DAS AÇÕES DE COMPETÊNCIAS DA GERES",
    "% DE MUNICÍPIOS VISITADOS",
    "% DE RESOLUÇÃO DAS AÇÕES DOS PLANOS DE AÇÃO",
    "% DE APROVEITAMENTO DAS COTAS DE EXAME DE IMAGEM (TOMOGRAFIA E RM)",
    "% DE CUMPRIMENTO DO PES POR QUADRIMESTRE",
    "% DE CUMPRIMENTO DO PES NO EXERCÍCIO",
    "ÍNDICE DE QUALIFICAÇÃO DAS AÇÕES DE VIGILÂNCIA",
    "TAXA DE PERDA PRIMÁRIA UPAE",
    "TAXA DE ABSENTEÍSMO",
    "% DE APROVEITAMENTO DAS COTAS DE CONSULTAS ESPECIALIZADAS",
    "% DOS MUNICÍPIOS COM OS INSTRUMENTOS DE GESTÃO DO SUS ATUALIZADOS",
    "% DE IMPLEMENTAÇÃO DO PLANEJAMENTO ESTRATÉGICO",
    "% ENGAJAMENTO DOS GESTORES NAS REUNIÕES DOS GRUPOS CONDUTORES MACRORREGIONAIS",
    "% DE INTEGRAÇÃO ENTRE GRUPOS CONDUTORES DE REDE E O PRI",
    "% PARTICIPAÇÃO DOS GESTORES NAS REUNIÕES DE CÂMARA TÉCNICA/CT CIR",
    "% PARTICIPAÇÃO DOS GESTORES NAS REUNIÕES DE CIR",
  ],
  macros: [
    {
      macro: "I MACRO",
      geres: [
        "I GERES: Recife",
        "II GERES: Limoeiro",
        "III GERES: Palmares",
        "XII GERES: Goiana",
      ],
    },
    {
      macro: "II MACRO",
      geres: ["IV GERES: Caruaru", "V GERES: Garanhuns"],
    },
    {
      macro: "III MACRO",
      geres: [
        "VI GERES: Arcoverde",
        "X GERES: Afogados da Ingazeira",
        "XI GERES: Serra Talhada",
      ],
    },
    {
      macro: "IV MACRO",
      geres: [
        "VII GERES: Salgueiro",
        "VIII GERES: Petrolina",
        "IX GERES: Ouricuri",
      ],
    },
  ],
};
