export const dados = {
  temasIndicadores: {
    "ADM/FINANCEIRO": [
      "% DE AÇÕES FINANCEIRAS EXECUTADAS EM TEMPO HÁBIL (60 DIAS)",
    ],
    "GERES PErcorre": [
      "TAXA DE SATISFAÇÃO DOS MUNICÍPIOS EM RELAÇÃO AO APOIO DAS GERES",
      "% DE RESOLUÇÃO DAS AÇÕES DE COMPETÊNCIAS DA GERES",
      "% DE MUNICÍPIOS VISITADOS",
    ],
    "PNI": [
      "NÚMERO DE MUNICÍPIOS QUE ATINGIRAM A COBERTURA VACINAL EM MENORES DE 2 ANOS",
      "% DE  MUNICÍPIOS QUE ENVIARAM DADOS PARA A RNDS"
    ],
    "PES": [
      "% DE CUMPRIMENTO DO PES NO EXERCÍCIO"
    ],
    "INOVAÇÃO/TECNOLOGIA": [
      "% DE ÁREAS TÉCNICAS COM SALAS DE SITUAÇÃO INSTITUIDAS"
    ],
    "GRUPOS ESPECIAIS": [
      "% DAS AÇÕES DE REGIONALIZAÇÃO DESENVOLVIDAS PELA GERES NO TERRITÓRIO"
    ],
    "ASSISTÊNCIA": [
      "% DE VINCULAÇÃO DA GESTANTE AO SERVIÇO DE REFERÊNCIA AO PARTO"
    ],
    "VIGILÂNCIA EPIDEMIOLÓGICA": [
      "% DE ÓBITOS  INFANTIS  E FETAIS INVESTIGADOS EM TEMPO OPORTUNO."
    ],
    "FILA /REGULAÇÃO": [
      "% DE REDUÇÃO DE FILA DE CONSULTAS",
      "% DE REDUÇÃO DE FILA DE EXAMES DE IMAGE"
    ],
    "VIGILÂNCIA SAÚDE DO TRABALHADOR": [
      "% DE INVESTIGAÇÃO EPIDEMIOLÓGICA DOS ÓBITOS POR ACIDENTE DE TRABALHO"
    ],
    "PERDA PRIMÁRIA / REGULAÇÃO": [
      "% DE APROVEITAMENTO DAS COTAS DE EXAME DE IMAGEM (TOMOGRAFIA E RM)"
    ],
    "ATENÇÃO PRIMÁRIA": [
      "% DE INTERNAÇÃO POR CAUSAS SENSÍVEIS A APS",
    ],
    "REGULAÇÃO": [
      "% DE ABSENTEISMO DE CONSULTAS E EXAMES",
      "% DE PERDA PRIMÁRIA DE COTAS DE CONSULTAS E EXAMES",
      "% DE PACIENTES COM RETORNO GARANTIDO NO SERVIÇO DAS UPAES"
    ],
    "ATENÇÃO À SAÚDE": [
      "% DE GESTANTES DE ALTO RISCO ACOMPANHADAS ADEQUADAMENTE",
      "TAXA DE MORTALIDADE MATERNA",
      "TAXA DE MORTALIDADE INFANTIL",
    ],
    "GERES PERCORRE": [
      "TAXA DE SATISFAÇÃO DOS MUNICÍPIOS EM RELAÇÃO AO APOIO DAS GERES",
      "% DE RESOLUÇÃO DAS AÇÕES DE COMPETÊNCIAS DA GERES NO PROGRAMA GERES PERCORRE",
    ],
    "GABINETE": [
      "TAXA DE MORTALIDADE POR CAUSAS EVITÁVEIS",
      "PROPORÇÃO DE NASCIDOS VIVOS DE MÃES COM 7 OU MAIS CONSULTAS DE PRÉ-NATAL",
      "TAXA DE MORTALIDADE POR ACIDENTES DE TRANSPORTE TERRESTRE"
    ],
    "JUNTOS PELA SAÚDE": [
      "% DE MORTALIDADE NÃO HOSPITALAR POR DCNT",
      "% DE MORTALIDADE NÃO HOSPITALAR NA INFÂNCIA",
      "% DE MORTALIDADE NÃO HOSPITALAR MATERNA",
      "% DE COBERTURA VACINAL POR REGIONAL",
      "% DE MORTES À ESCLARECER POR REGIONAL",
      "% DE FILA DE ESPERA POR REGIONAL"
    ],
  },
};
