export const dados = {
  temasIndicadores: {
    "FINANCEIRO / ORÇAMENTO": [
      "% DE EXECUÇÃO DO ORÇAMENTO POR REGIONAL",
    ],
    "GERES PErcorre": [
      "TAXA DE SATISFAÇÃO DOS MUNICÍPIOS EM RELAÇÃO AO APOIO DAS GERES",
      "% DE RESOLUÇÃO DAS AÇÕES DE COMPETÊNCIAS DA GERES",
      "% DE MUNICÍPIOS VISITADOS",
    ],
    "PERDA PRIMÁRIA / REGULAÇÃO": [
      "% DE APROVEITAMENTO DAS COTAS DE EXAME DE IMAGEM (TOMOGRAFIA E RM)",
      "TAXA DE PERDA PRIMÁRIA UPAE",
      "TAXA DE ABSENTEÍSMO",
    ],
    "PES": [
      "% DE CUMPRIMENTO DO PES POR QUADRIMESTRE",
      "% DE CUMPRIMENTO DO PES NO EXERCÍCIO",
    ],
    "PQAVS": [
      "ÍNDICE DE QUALIFICAÇÃO DAS AÇÕES DE VIGILÂNCIA",
    ],
    "REGULAÇÃO": [
      "% DE APROVEITAMENTO DAS COTAS DE CONSULTAS ESPECIALIZADAS",
    ],
    "PLANEJAMENTO": [
      "% DOS MUNICÍPIOS COM OS INSTRUMENTOS DE GESTÃO DO SUS ATUALIZADOS",
      "% DE IMPLEMENTAÇÃO DO PLANEJAMENTO ESTRATÉGICO",
    ],
    "PRI/GOVERNANÇA": [
      "% ENGAJAMENTO DOS GESTORES NAS REUNIÕES DOS GRUPOS CONDUTORES MACRORREGIONAIS",
      "% DE INTEGRAÇÃO ENTRE GRUPOS CONDUTORES DE REDE E O PRI",
    ],
    "GOVERNANÇA": [
      "% PARTICIPAÇÃO DOS GESTORES NAS REUNIÕES DE CÂMARA TÉCNICA/CT CIR",
      "% PARTICIPAÇÃO DOS GESTORES NAS REUNIÕES DE CIR",
    ],
  },
};
